//! Tusk actions: every command in the palette / keymap goes through here.
//!
//! Keybindings are bound in [`bind_keys`] with the `TuskApp` key context.
//! Views handle them with `.on_action(cx.listener(...))`.

use gpui_kit::*;

gpui_kit::actions!(
    tusk,
    [
        TogglePalette,
        QuickOpenTables,
        NewConnection,
        QuickConnect,
        TestConnection,
        SaveConnection,
        ConnectNow,
        ConnectRecent1,
        ConnectRecent2,
        ConnectRecent3,
        ConnectRecent4,
        ConnectRecent5,
        CloseOverlay,
        NewSqlTab,
        RunCurrent,
        RunAll,
        RefreshActive,
        CloseTab,
        SaveChanges,
        DeleteSelection,
        ToggleFilters,
        ToggleConsole,
        ShowCompletions,
        ToggleRowDetail,
        ToggleAiPanel,
        SendToChat,
        AiPickUp,
        AiPickDown,
        AiPickConfirm,
        AiEscape,
        ToggleLineComment,
        ProcessList,
        SearchInDatabase,
        UserManagement,
        ToggleResultsPane,
        SplitPaneRight,
        NextPane,
        ShowAllTabs,
        OpenSqlFile,
        SaveQueryAs,
        ImportCsv,
        ImportJson,
        ImportSqlDump,
        ImportDockerCompose,
        ExportTables,
        ExportActiveTable,
        GridCopy,
        GridCopyCells,
        GridPaste,
        ToggleBlockComment,
        MakeUpperCase,
        MakeLowerCase,
        Capitalize,
        IncreaseFontSize,
        DecreaseFontSize,
        ResetFontSize,
        NextTab,
        PrevTab,
        TabAt6,
        TabAt7,
        TabAt8,
        TabAtLast,
        GoBack,
        GoForward,
        ReloadWorkspace,
        Reconnect,
        CloseAllTabs,
        DiscardChanges,
        PreviewChanges,
        OpenDatabase,
        OpenConnection,
        TypePickUp,
        TypePickDown,
        TypePickConfirm,
        ToggleProblems,
        ShowHistory,
        Quit,
        HideApp,
        Disconnect,
        ShowTablesPanel,
        ShowViewsPanel,
        ShowFunctionsPanel,
        ToggleSidebar,
        ShowStructure,
        ShowData,
        OpenSettings,
        CheckForUpdates,
        ShowAbout,
        RestartToUpdate,
        OpenConnections,
        BackupDatabase,
        RestoreDatabase,
        PrevPage,
        NextPage,
        FilterInsert,
        FilterRemove,
        FilterApplyAll,
        FilterUp,
        FilterDown,
        FilterColumns,
        FilterOperators,
        FilterToggle,
        FilterExit,
        GridEdit,
        GridInsertRow,
        GridDuplicateRow,
        GridSetNull,
        GridEditNext,
        GridEditPrev,
        MinimizeWindow,
        ZoomWindow,
        ToggleFullScreen,
        BringAllToFront,
        OpenHelp,
        ReportIssue
    ]
);

/// Global keymap. Contexts: `TuskApp` (always), actions check their own screen.
pub fn bind_keys(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("cmd-shift-p", TogglePalette, Some("TuskApp")),
        KeyBinding::new("cmd-p", QuickOpenTables, Some("TuskApp")),
        KeyBinding::new("cmd-k", OpenDatabase, Some("TuskApp")),
        KeyBinding::new("cmd-shift-k", OpenConnection, Some("TuskApp")),
        KeyBinding::new("cmd-n", NewConnection, Some("TuskApp")),
        KeyBinding::new("cmd-o", OpenSqlFile, Some("TuskApp")),
        KeyBinding::new("cmd-shift-s", SaveQueryAs, Some("TuskApp")),
        KeyBinding::new("cmd-shift-o", OpenConnections, Some("TuskApp")),
        // Filter bar keys (shown in the bar). "FilterBar > Input" so they win
        // over the text field's own ⌘← / ⌘→ / ⌘↵ while typing a filter.
        KeyBinding::new("cmd-i", FilterInsert, Some("FilterBar > Input")),
        KeyBinding::new("cmd-shift-i", FilterRemove, Some("FilterBar > Input")),
        KeyBinding::new("cmd-enter", FilterApplyAll, Some("FilterBar > Input")),
        KeyBinding::new("cmd-up", FilterUp, Some("FilterBar > Input")),
        KeyBinding::new("cmd-down", FilterDown, Some("FilterBar > Input")),
        KeyBinding::new("cmd-left", FilterColumns, Some("FilterBar > Input")),
        KeyBinding::new("cmd-right", FilterOperators, Some("FilterBar > Input")),
        KeyBinding::new("cmd-b", FilterToggle, Some("FilterBar > Input")),
        KeyBinding::new("escape", FilterExit, Some("FilterBar > Input")),
        // Grid editing: Enter edits the selected cell, Tab / ⇧Tab while
        // editing save and move on, ⌘I new row, ⌘D duplicate, ⌘⌫ NULL.
        KeyBinding::new("enter", GridEdit, Some("DataTable")),
        KeyBinding::new("cmd-i", GridInsertRow, Some("DataTable")),
        KeyBinding::new("cmd-d", GridDuplicateRow, Some("DataTable")),
        KeyBinding::new("cmd-backspace", GridSetNull, Some("DataTable")),
        KeyBinding::new("tab", GridEditNext, Some("DataTable > Input")),
        KeyBinding::new("shift-tab", GridEditPrev, Some("DataTable > Input")),
        // Grid paging (text fields keep ⌘← / ⌘→ for line start / end).
        KeyBinding::new("cmd-left", PrevPage, Some("DataTable")),
        KeyBinding::new("cmd-right", NextPage, Some("DataTable")),
        KeyBinding::new("cmd-1", ConnectRecent1, Some("TuskApp")),
        KeyBinding::new("cmd-2", ConnectRecent2, Some("TuskApp")),
        KeyBinding::new("cmd-3", ConnectRecent3, Some("TuskApp")),
        KeyBinding::new("cmd-4", ConnectRecent4, Some("TuskApp")),
        KeyBinding::new("cmd-5", ConnectRecent5, Some("TuskApp")),
        KeyBinding::new("escape", CloseOverlay, Some("TuskApp")),
        // A cell / structure / index editor: Escape cancels the edit (the
        // input would otherwise keep it open).
        KeyBinding::new("escape", CloseOverlay, Some("DataTable > Input")),
        KeyBinding::new("escape", CloseOverlay, Some("PreviewSheet > Input")),
        KeyBinding::new("cmd-t", NewSqlTab, Some("TuskApp")),
        KeyBinding::new("cmd-w", CloseTab, Some("TuskApp")),
        KeyBinding::new("cmd-r", ReloadWorkspace, Some("TuskApp")),
        KeyBinding::new("cmd-alt-r", RefreshActive, Some("TuskApp")),
        KeyBinding::new("cmd-shift-r", Reconnect, Some("TuskApp")),
        KeyBinding::new("cmd-shift-\\", ShowAllTabs, Some("TuskApp")),
        KeyBinding::new("cmd-shift-d", SplitPaneRight, Some("TuskApp")),
        KeyBinding::new("cmd-alt-]", NextPane, Some("TuskApp")),
        KeyBinding::new("cmd-alt-[", NextPane, Some("TuskApp")),
        KeyBinding::new("cmd-alt-ü", NextPane, Some("TuskApp")),
        KeyBinding::new("cmd-alt-ğ", NextPane, Some("TuskApp")),
        KeyBinding::new("cmd-.", ProcessList, Some("TuskApp")),
        KeyBinding::new("cmd-.", ProcessList, Some("DataTable")),
        // The editor's own ⌘. (code actions) has nothing to offer for SQL.
        KeyBinding::new("cmd-.", ProcessList, Some("TuskApp > Input")),
        KeyBinding::new("escape", CloseOverlay, Some("ProcessList")),
        KeyBinding::new("escape", CloseOverlay, Some("DbSearch > Input")),
        KeyBinding::new("cmd-alt-.", Disconnect, Some("TuskApp")),
        KeyBinding::new("cmd-]", NextTab, Some("TuskApp")),
        KeyBinding::new("cmd-[", PrevTab, Some("TuskApp")),
        KeyBinding::new("cmd-6", TabAt6, Some("TuskApp")),
        KeyBinding::new("cmd-7", TabAt7, Some("TuskApp")),
        KeyBinding::new("cmd-8", TabAt8, Some("TuskApp")),
        KeyBinding::new("cmd-9", TabAtLast, Some("TuskApp")),
        KeyBinding::new("ctrl-cmd-left", GoBack, Some("TuskApp")),
        KeyBinding::new("ctrl-cmd-right", GoForward, Some("TuskApp")),
        KeyBinding::new("ctrl-cmd-[", ShowData, Some("TuskApp")),
        KeyBinding::new("ctrl-cmd-]", ShowStructure, Some("TuskApp")),
        // Turkish Q layout: the [ / ] keys type ğ / ü (TablePlus gets these
        // through the menu's key-equivalent mapping).
        KeyBinding::new("cmd-ü", NextTab, Some("TuskApp")),
        KeyBinding::new("cmd-ğ", PrevTab, Some("TuskApp")),
        KeyBinding::new("ctrl-cmd-ğ", ShowData, Some("TuskApp")),
        KeyBinding::new("ctrl-cmd-ü", ShowStructure, Some("TuskApp")),
        KeyBinding::new("cmd-shift-backspace", DiscardChanges, Some("TuskApp")),
        KeyBinding::new("cmd-alt-p", PreviewChanges, Some("TuskApp")),
        // ⌘↵ runs the statement under the cursor (or the
        // selection), ⇧⌘↵ runs the whole editor.
        KeyBinding::new("cmd-enter", RunCurrent, Some("TuskApp")),
        KeyBinding::new("cmd-shift-enter", RunAll, Some("TuskApp")),
        // The gpui-base input layer binds secondary-enter (cmd+enter on macOS)
        // in its own "Input" context, which shadows TuskApp while the SQL
        // editor is focused — exactly when users press it. Bind there too so
        // ⌘↵ always runs. (The keyboard action below ignores it while the
        // command palette is open.)
        KeyBinding::new("cmd-enter", RunCurrent, Some("Input")),
        KeyBinding::new("cmd-shift-enter", RunAll, Some("Input")),
        // ⌃Space: completions at the cursor, without typing a character.
        KeyBinding::new("ctrl-space", ShowCompletions, Some("Input")),
        KeyBinding::new("cmd-/", ToggleLineComment, Some("Input")),
        KeyBinding::new("cmd-alt-/", ToggleBlockComment, Some("Input")),
        // Turkish Q: "/" is shift-7, which arrives as the US shifted key "&".
        KeyBinding::new("cmd-&", ToggleLineComment, Some("Input")),
        KeyBinding::new("cmd-=", IncreaseFontSize, Some("TuskApp")),
        KeyBinding::new("cmd-+", IncreaseFontSize, Some("TuskApp")),
        // Turkish Q: "=" is shift-0, which arrives as the US shifted key ")".
        KeyBinding::new("cmd-)", IncreaseFontSize, Some("TuskApp")),
        KeyBinding::new("cmd--", DecreaseFontSize, Some("TuskApp")),
        KeyBinding::new("cmd-0", ResetFontSize, Some("TuskApp")),
        // Structure data_type editor: arrows move through the type list,
        // Enter takes the highlighted type (registered after the kit, so
        // these win over the input's own up / down / enter).
        KeyBinding::new("up", TypePickUp, Some("TypePicker > Input")),
        // AI composer: ↑↓ / Tab pick from the `/` and `@` lists, Esc stops a reply.
        KeyBinding::new("up", AiPickUp, Some("AiComposer > Input")),
        KeyBinding::new("down", AiPickDown, Some("AiComposer > Input")),
        KeyBinding::new("tab", AiPickConfirm, Some("AiComposer > Input")),
        KeyBinding::new("escape", AiEscape, Some("AiComposer > Input")),
        KeyBinding::new("up", AiPickUp, Some("AiOptionPicker > Input")),
        KeyBinding::new("down", AiPickDown, Some("AiOptionPicker > Input")),
        KeyBinding::new("cmd-l", ToggleAiPanel, Some("TuskApp")),
        KeyBinding::new("cmd-shift-l", SendToChat, Some("TuskApp")),
        KeyBinding::new("down", TypePickDown, Some("TypePicker > Input")),
        KeyBinding::new("enter", TypePickConfirm, Some("TypePicker > Input")),
        // ⌘S commits every pending grid / structure / sidebar change.
        KeyBinding::new("cmd-s", SaveChanges, Some("TuskApp")),
        KeyBinding::new("cmd-z", gpui_kit::component::input::Undo, Some("TuskApp")),
        KeyBinding::new(
            "cmd-shift-z",
            gpui_kit::component::input::Redo,
            Some("TuskApp"),
        ),
        KeyBinding::new("cmd-q", Quit, None),
        KeyBinding::new("cmd-h", HideApp, None),
        KeyBinding::new("cmd-m", MinimizeWindow, None),
        KeyBinding::new("ctrl-cmd-f", ToggleFullScreen, None),
        KeyBinding::new("cmd-,", OpenSettings, None),
        KeyBinding::new("cmd-b", ToggleSidebar, Some("TuskApp")),
        KeyBinding::new("cmd-shift-1", ShowTablesPanel, Some("TuskApp")),
        KeyBinding::new("cmd-shift-2", ShowViewsPanel, Some("TuskApp")),
        KeyBinding::new("cmd-shift-3", ShowFunctionsPanel, Some("TuskApp")),
        KeyBinding::new("cmd-alt-1", ShowData, Some("TuskApp")),
        KeyBinding::new("cmd-alt-2", ShowStructure, Some("TuskApp")),
        KeyBinding::new("cmd-f", ToggleFilters, Some("TuskApp")),
        KeyBinding::new("cmd-shift-c", ToggleConsole, Some("TuskApp")),
        KeyBinding::new("cmd-shift-m", ToggleProblems, Some("TuskApp")),
        KeyBinding::new("cmd-y", ShowHistory, Some("TuskApp")),
        KeyBinding::new("cmd-shift-j", ToggleRowDetail, Some("TuskApp")),
        KeyBinding::new("cmd-shift-j", ToggleRowDetail, Some("DataTable")),
        // The grid and the editor shadow TuskApp for these; bind there too.
        // In the grid ⇧⌘C copies the selected cells (the console keeps ⇧⌘C
        // everywhere else).
        KeyBinding::new("cmd-c", GridCopy, Some("DataTable")),
        KeyBinding::new("cmd-shift-c", GridCopyCells, Some("DataTable")),
        KeyBinding::new("cmd-shift-v", GridPaste, Some("DataTable")),
        KeyBinding::new("cmd-shift-c", ToggleConsole, Some("Input")),
        KeyBinding::new("cmd-shift-m", ToggleProblems, Some("DataTable")),
        KeyBinding::new("cmd-shift-m", ToggleProblems, Some("Input")),
        KeyBinding::new("cmd-y", ShowHistory, Some("DataTable")),
        KeyBinding::new("cmd-y", ShowHistory, Some("Input")),
        // Delete marks the selected row / column / object red (saved with ⌘S).
        // Scoped to the grid and sidebar so text inputs keep their backspace.
        KeyBinding::new("backspace", DeleteSelection, Some("DataTable")),
        KeyBinding::new("delete", DeleteSelection, Some("DataTable")),
        KeyBinding::new("backspace", DeleteSelection, Some("Sidebar")),
        KeyBinding::new("delete", DeleteSelection, Some("Sidebar")),
        // Phase 6/7 actions (registered early so the palette can list them):
        // cmd-t / cmd-w / cmd-r / cmd-enter are bound when tabs exist.
    ]);
}
